from __future__ import annotations

from app.application import create_app
from app.web.routes.auth import login_page, login_submit, logout
from app.web.routes.health import healthz
from app.web.routes.shows import (
    add_guide_row_route,
    approve_show_route,
    build_trade_show_guide_route,
    configure_smartlead_route,
    create_smartlead_campaign_route,
    confirm_scanned_trade_shows_route,
    delete_show_leads,
    delete_show,
    delete_guide_row_route,
    download_enriched_export,
    download_export,
    download_guide_workbook,
    download_smartlead_export,
    launch_show_route,
    pause_show_route,
    rebuild_smartlead_campaign_route,
    remove_show_from_queue_route,
    run_show_now,
    scan_upcoming_trade_shows_route,
    scrape_pending_shows_route,
    scrape_selected_shows,
    show_guide,
    show_dashboard,
    show_detail,
    sync_show_from_clay_route,
    upload_guide_workbook_route,
    update_guide_row_route,
    update_show_route,
)
from app.web.routes.workflow import (
    add_single_show,
    bulk_scrape_download,
    bulk_scrape_status,
    dashboard,
    delete_all_shows,
    import_shows,
    scrape_many_shows,
    scrape_single_show,
)


app = create_app()


__all__ = [
    "app",
    "healthz",
    "login_page",
    "login_submit",
    "logout",
    "dashboard",
    "show_dashboard",
    "show_guide",
    "import_shows",
    "add_single_show",
    "scrape_single_show",
    "scrape_many_shows",
    "bulk_scrape_status",
    "bulk_scrape_download",
    "delete_all_shows",
    "show_detail",
    "update_show_route",
    "delete_show",
    "delete_show_leads",
    "run_show_now",
    "remove_show_from_queue_route",
    "scan_upcoming_trade_shows_route",
    "scrape_pending_shows_route",
    "scrape_selected_shows",
    "confirm_scanned_trade_shows_route",
    "download_export",
    "download_guide_workbook",
    "download_enriched_export",
    "download_smartlead_export",
    "approve_show_route",
    "sync_show_from_clay_route",
    "launch_show_route",
    "configure_smartlead_route",
    "create_smartlead_campaign_route",
    "pause_show_route",
    "rebuild_smartlead_campaign_route",
    "build_trade_show_guide_route",
    "upload_guide_workbook_route",
    "add_guide_row_route",
    "update_guide_row_route",
    "delete_guide_row_route",
]
